version: '3'
services:
  portal-core-db:
    image: postgres
    volumes:
      - /app/portal/core/db/config:/etc/postgresql
      - /app/portal/core/logs:/var/log/postgresql
      - /app/portal/core/db/databases:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: portal-core
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: portal-core
